language: android
sudo: true
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

addons:
  sources:
    - ubuntu-toolchain-r-test
  apt_packages:
    - pandoc
    - wget
    - pkg-config
  artifacts:
    paths:
      - $HOME/tensorflow/bazel-bin/tensorflow/contrib/android/libtensorflow_inference.so
      - $HOME/tensorflow/bazel-bin/tensorflow/libtensorflow.so

before_install:
  - wget -q https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip
  - unzip -qq android-ndk-r12b-linux-x86_64.zip -d $HOME
  - mv $HOME/android-ndk-r12b $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root
  - wget -q https://github.com/bazelbuild/bazel/releases/download/0.5.4/bazel_0.5.4-linux-x86_64.deb
  - sudo dpkg -i bazel_0.5.4-linux-x86_64.deb
  - git clone --recurse-submodules https://github.com/tensorflow/tensorflow.git $HOME/tensorflow
  - cd $HOME/tensorflow && git checkout v1.3.0 && sed -i '\@https://github.com/google/protobuf/archive/0b059a3d8a8f8aa40dde7bea55edca4ec5dfea66.tar.gz@d' tensorflow/workspace.bzl
  - cp $TRAVIS_BUILD_DIR/WORKSPACE $HOME/tensorflow/WORKSPACE

install:

script:
  - cd $HOME/tensorflow && bazel build --verbose_failures //tensorflow/contrib/android:libtensorflow_inference.so //tensorflow:libtensorflow.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a

