language: android
sudo: true
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

addons:
  sources:
    - ubuntu-toolchain-r-test
  apt_packages:
    - pandoc
    - wget
    - pkg-config
    - ant
  artifacts:
    paths:
      - $HOME/tensorflow/bazel-bin/tensorflow/contrib/android/libtensorflow_inference.so

before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root
  - wget https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel_0.3.1-linux-x86_64.deb
  - sudo dpkg -i bazel_0.3.1-linux-x86_64.deb
  - git clone https://github.com/tensorflow/tensorflow.git $HOME/tensorflow
  - cd $HOME/tensorflow && git checkout v1.3.0

scripts:
  - cd $HOME/tensorflow && bazel build //tensorflow/contrib/android:libtensorflow_inference.so --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a

